# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];

  boot.kernelModules = [ "kvm-intel" "wl" ]; # "wl": added for MacBook Air (13-inch,Early 2014)

  # broadcom_sta: added for MacBook Air (13-inch,Early 2014)
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  nixpkgs.config.permittedInsecurePackages = [
    # "broadcom-sta-6.30.223.271-59-6.18.40"
    "broadcom-sta-6.30.223.271-59-6.18.39"
  ];

  boot.initrd.luks.devices."luks-d705aafd-45b5-486a-9adb-58d1774ed927".device = "/dev/disk/by-uuid/d705aafd-45b5-486a-9adb-58d1774ed927";
  boot.initrd.luks.devices."luks-c598058e-96ed-4cfd-8b52-cae912ea8c4b".device = "/dev/disk/by-uuid/c598058e-96ed-4cfd-8b52-cae912ea8c4b";

  fileSystems."/" =
    { device = "/dev/mapper/luks-d705aafd-45b5-486a-9adb-58d1774ed927";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DF55-0A3F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c598058e-96ed-4cfd-8b52-cae912ea8c4b"; }
    ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
